######################################################################
# Automatically generated by qmake (2.01a) Tue Aug 17 19:44:36 2010
######################################################################
QT += webkit
TEMPLATE = app
TARGET = 
DEPENDPATH += . build src src/data
INCLUDEPATH += . src

# Input
HEADERS += src/mainwindow.h
SOURCES += src/main.cpp src/mainwindow.cpp
RESOURCES += src/data/data.qrc
