.TH SIMBA 1

.SH NAME
.B simba
\- a simple program for leo.org

.SH SYNOPSIS
.B simba
[OPTIONS]

.SH DESCRIPTION
.B simba
is for the better use of leo.org

.SH OPTIONS
.TP
.B --version, -v (not implement)
Display version information

.SH FILES
.TP
.I ~/.config/simba/simba.conf
Text file to store the preferences.

.SH SEE ALSO
.B Simba
homepage: \%http://azd325.github.com/simba/

.B Simba
development: \%https://github.com/Azd325/simba

.SH BUGS
If you find a bug, please report it at \%https://github.com/Azd325/simba/issues

.SH AUTHORS
Tim Kleinschmidt
